In [9]:
import pandas as pd
import re
%matplotlib inline

In [2]:
df = pd.read_csv('arms_data_raw.csv')
df.head()

,link,location,make,model,name
0,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Benton, TN",Remington,11-87 Premier,Remington 11-87 Premier Semi-Automatic 12 Gaug...
1,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",REMINGTON,700,REMINGTON 700 .270
2,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",REMINGTON,700,"REMINGTON MODEL 700, .270"
3,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Benton, TN",Smith and Wesson,SD9 VE,Smith and Wesson SD9 VE 9mm Semi-Auto Handgun
4,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Benton, TN",EAA,Windicator,EAA Windicator .38 Special / .357 Magnum Revolver

In [3]:
df.shape

(53, 5)

In [10]:
df[df.name.str.contains('[Ss]hotgun')]

,link,location,make,model,name
0,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Benton, TN",Remington,11-87 Premier,Remington 11-87 Premier Semi-Automatic 12 Gaug...
5,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Benton, TN",Remington,870 Express Magnum,Remington 870 Express Magnum 12 Gauge Shotgun
8,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Benton, TN",Boito,BR7,Boito BR7 20 Gauge Double Barrel Shotgun
45,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Benton, TN",Spesco Corporation,151,Spesco Model 151 .410 Gauge Shotgun

In [18]:
df[df.name.str.contains('bow')]

Empty DataFrame
Columns: [link, location, make, model, name]
Index: []

In [20]:
df.make.value_counts()

REMINGTON                  6
BARNETT                    4
BOW TECH                   3
BEAR                       2
Remington                  2
Hi-Standard                2
HORTON                     2
TEN POINT                  2
MATTHEWS                   2
PSE                        2
RUGER                      2
Taurus                     1
NEW ENGLAND                1
ALPINE                     1
EAA                        1
SMITH & WESSON             1
Charter Arms               1
Mossberg                   1
Boito                      1
MISSION                    1
PARKER                     1
Spesco Corporation         1
CENTER POINT               1
CVA                        1
JAGUAR                     1
Smith and Wesson           1
EXCALIBUR                  1
Beretta                    1
BPI                        1
MOSSBERG                   1
Marlin Firearms Company    1
CARBON EXPRESS             1
Sterling Arms              1
SAVAGE                     1
HIGH COUNTRY               1
Name: make, dtype: int64

In [26]:
df.make = df.make.str.lower()

In [31]:
df.make = df.make.str.replace('&', 'and')

In [32]:
df.make.value_counts()

remington                  8
barnett                    4
bow tech                   3
ten point                  2
pse                        2
bear                       2
horton                     2
smith and wesson           2
hi-standard                2
mossberg                   2
ruger                      2
matthews                   2
new england                1
savage                     1
carbon express             1
taurus                     1
cva                        1
eaa                        1
alpine                     1
marlin firearms company    1
spesco corporation         1
parker                     1
charter arms               1
sterling arms              1
boito                      1
bpi                        1
mission                    1
center point               1
beretta                    1
jaguar                     1
excalibur                  1
high country               1
Name: make, dtype: int64

In [33]:
df.location.value_counts()

Nashville, TN    39
Benton, TN       14
Name: location, dtype: int64

In [35]:
df.name = df.name.str.lower()

In [40]:
df[df.name.str.contains('bow')]

,link,location,make,model,name
18,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",ten point,INVADER G3,ten point wicked ridge invader g3 crossbow
20,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",bow tech,CARBON ICON,bow tech carbon icon bow
24,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",bow tech,STRYKER,bow tech stryker crossbow
25,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",pse,TAC ELITE,pse tac elite crossbow
26,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",pse,VIPER COPPERHEAD,pse viper copperhead crossbow
27,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",horton,NaN,horton crossbow
28,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",parker,NaN,parker crossbow
29,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",barnett,QUAD 400,barnett quad 400 crossbow
30,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",mission,RIOT,mission riot compound bow
31,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",barnett,QUAD 400,barnett quad 400 crossbow
33,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",barnett,RHINO,barnett rhino crossbow
34,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",barnett,BROTHERHOOD M4,barnett brotherhood m4 crossbow
35,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",center point,NaN,center point crossbow
36,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",excalibur,EQUINOX,excalibur real tree equinox crossbow
37,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",carbon express,X-FORCE 350,carbon express x-force 350 crossbow
39,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",matthews,NaN,matthews compound bow
40,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",matthews,NaN,matthews compound bow
42,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",horton,NaN,horton crossbow
44,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",jaguar,NaN,jaguar crossbow
46,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",ten point,WOODSMAN,ten point woodsman crossbow
48,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",alpine,RIDGE RUNNER,alpine ridge runner bow
49,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",bow tech,DIAMOND RAZOR EDGE,bow tech diamond razor edge bow
50,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",high country,TSS,high country tss bow
51,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",bear,CRUX,bear crux compound bow
52,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",bear,THE TRUTH,bear the truth bow

In [46]:
df[df.name.str.contains('gun')]

,link,location,make,model,name
0,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Benton, TN",remington,11-87 Premier,remington 11-87 premier semi-automatic 12 gaug...
3,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Benton, TN",smith and wesson,SD9 VE,smith and wesson sd9 ve 9mm semi-auto handgun
5,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Benton, TN",remington,870 Express Magnum,remington 870 express magnum 12 gauge shotgun
8,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Benton, TN",boito,BR7,boito br7 20 gauge double barrel shotgun
15,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Benton, TN",beretta,Bobcat 21A,beretta bobcat model 21a -- .22 lr semi-auto h...
16,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Benton, TN",taurus,PT 738,"taurus tcp pt 738, .380 acp semi-auto handgun"
21,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Benton, TN",sterling arms,.25 Stainless,sterling .25 caliber stainless semi-auto hangun
43,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Nashville, TN",new england,12 GA SB1011,new england firearms 12 ga shotgun
45,https://www.govdeals.com/index.cfm?fa=Main.Ite...,"Benton, TN",spesco corporation,151,spesco model 151 .410 gauge shotgun

In [47]:
df.model.value_counts()

700                   2
Double Nine W-104     2
870; 12 GU.PUMP       2
QUAD 400              2
INVADER G3            1
PT 738                1
VIPER COPPERHEAD      1
.243                  1
EQUINOX               1
WOLF                  1
Model 101             1
WOODSMAN              1
Pathfinder            1
.25 Stainless         1
SD9 VE                1
RHINO                 1
CARBON ICON           1
Windicator            1
TSS                   1
MODEL 9200            1
BR7                   1
EASTFIELD 916         1
TAC ELITE             1
BROTHERHOOD M4        1
715T                  1
Bobcat 21A            1
11-87 Premier         1
DIAMOND RAZOR EDGE    1
STRYKER               1
THE TRUTH             1
CRUX                  1
RIDGE RUNNER          1
RIOT                  1
742                   1
870;12 GU.PUMP        1
12 GA SB1011          1
151                   1
870 Express Magnum    1
X-FORCE 350           1
NEW FRONTIER          1
110                   1
Name: model, dtype: int64

In [48]:
df.model = df.model.str.lower()

In [49]:
df.to_csv('arms_data_clean.csv', index=False)